// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package jsonmaporstruct

import (
	"github.com/mailru/easyjson/jlexer"
	"github.com/mailru/easyjson/jwriter"
)

func (Object) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*Object) UnmarshalJSON([]byte) error        { return nil }
func (Object) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*Object) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Object *Object

func (Object2) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*Object2) UnmarshalJSON([]byte) error        { return nil }
func (Object2) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*Object2) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Object2 *Object2

func (Object3) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*Object3) UnmarshalJSON([]byte) error        { return nil }
func (Object3) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*Object3) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Object3 *Object3
